# PYTHIA configuration file.
# Generated on Mon Apr 26 13:52:08 CEST 2021 with the user supplied options:
# --prefix=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/pythia8/245-b48b5/x86_64-centos7-gcc9-opt
# --with-hepmc2=/cvmfs/sft.cern.ch/lcg/releases/HepMC/2.06.11-d5a39/x86_64-centos7-gcc9-opt
# --with-lhapdf6=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/lhapdf/6.3.0-5d46a/x86_64-centos7-gcc9-opt
# --enable-shared
# --cxx-common=-std=c++17 -O2 -pedantic -W -Wall -Wshadow -fPIC

# Install directory prefixes.
PREFIX_BIN=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/pythia8/245-b48b5/x86_64-centos7-gcc9-opt/bin
PREFIX_INCLUDE=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/pythia8/245-b48b5/x86_64-centos7-gcc9-opt/include
PREFIX_LIB=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/pythia8/245-b48b5/x86_64-centos7-gcc9-opt/lib
PREFIX_SHARE=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/pythia8/245-b48b5/x86_64-centos7-gcc9-opt/share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=true
CXX=/cvmfs/sft.cern.ch/lcg/releases/gcc/9.2.0-afc57/x86_64-centos7/bin/g++
CXX_COMMON=-std=c++17 -O2 -pedantic -W -Wall -Wshadow -fPIC
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=
EVTGEN_LIB=

# FASTJET3 configuration.
FASTJET3_USE=false
FASTJET3_BIN=
FASTJET3_INCLUDE=
FASTJET3_LIB=

# HEPMC2 configuration.
HEPMC2_USE=true
HEPMC2_BIN=/cvmfs/sft.cern.ch/lcg/releases/HepMC/2.06.11-d5a39/x86_64-centos7-gcc9-opt/bin
HEPMC2_INCLUDE=/cvmfs/sft.cern.ch/lcg/releases/HepMC/2.06.11-d5a39/x86_64-centos7-gcc9-opt/include
HEPMC2_LIB=/cvmfs/sft.cern.ch/lcg/releases/HepMC/2.06.11-d5a39/x86_64-centos7-gcc9-opt/lib

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=
HEPMC3_LIB=

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=
LHAPDF5_LIB=

# LHAPDF6 configuration.
LHAPDF6_USE=true
LHAPDF6_BIN=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/lhapdf/6.3.0-5d46a/x86_64-centos7-gcc9-opt/bin
LHAPDF6_INCLUDE=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/lhapdf/6.3.0-5d46a/x86_64-centos7-gcc9-opt/include
LHAPDF6_LIB=/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/lhapdf/6.3.0-5d46a/x86_64-centos7-gcc9-opt/lib

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=
POWHEG_LIB=

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=
PROMC_LIB=

# ROOT configuration.
ROOT_USE=true
ROOT_BIN=/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc9-opt/bin
ROOT_LIBS=/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc9-opt/lib
CXX_ROOT=/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc9-opt/bin
ROOT_INCLUDE=/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc9-opt/include
ROOT_LIB=/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.24.00-a725e/x86_64-centos7-gcc9-opt/lib

# GZIP configuration.
GZIP_USE=false
GZIP_BIN=
GZIP_INCLUDE=
GZIP_LIB=

# BOOST configuration.
BOOST_USE=false
BOOST_BIN=
BOOST_INCLUDE=
BOOST_LIB=

# PYTHON configuration.
PYTHON_USE=false
PYTHON_BIN=
PYTHON_INCLUDE=
PYTHON_LIB=
